# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1200
Set Height 600

Set WindowBar Rings
Set Theme "Catppuccin Frappe"

Set Margin 60
Set MarginFill "#6B50FF"
Set BorderRadius 10


# Type a command in the terminal.
Type "ls"
# Type "./bin/Release/net8.0/win-x64/Resumer.exe"

# Pause for dramatic effect...
# Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s
