# good ref:https://github.com/ruby/ruby-dev-builder/blob/b0bf59a17c17985d4692243d4689c273f6348fa5/.github/workflows/build.yml#L40
name: Draft Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string


env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_NAME: ${{ github.event.inputs.tag || github.ref_name }}

jobs:

  setup-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: release
        run: |
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            release_name=${{ github.ref_name }}
          else
            release_name=${{ github.event.inputs.tag }}
          fi
          gh release create $release_name --draft --generate-notes
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
    outputs:
      release_name: ${{ steps.release.outputs.release_name }}

  add-assets:
    name: Create and upload executables
    needs: setup-release
    uses: ./.github/workflows/generate_executables.yml
    with:
      tag: ${{ needs.setup-release.outputs.release_name }}
    secrets: inherit

  upload-assets:
    name: Upload Release Asset
    needs: [setup-release, add-assets]
    runs-on: ubuntu-latest
    # needs: add-assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - name: Upload assets to release draft
        run: gh release upload ${{ needs.setup-release.outputs.release_name }} ${{ needs.add-assets.outputs.assets }}