# good ref:https://github.com/ruby/ruby-dev-builder/blob/b0bf59a17c17985d4692243d4689c273f6348fa5/.github/workflows/build.yml#L40
name: .NET

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      version:
        description: platform to publish
        required: false
        type: string
        default: 'linux-x64'
        options:
          - win-x64
          - win-x86
          - win-arm64
          - linux-x64
          - linux-musl-x64
          - linux-musl-arm64
          - linux-arm
          - linux-arm64
          - linux-bionic-arm64
          - osx-x64
          - osx-arm64

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]


    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish Resumer/ --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: ./publish/

      - name: zip
        run: bash zip -r ../${{ matrix.os }}_resumer_${{ github.ref_name }}.zip ../publish
        working-directory: ./publish

      - name: zip files
        shell: pwsh
        run: |
            if ($env:RUNNER_OS -eq "Windows") {
              7z a ../${{ matrix.os }}_resumer_${{ github.ref_name }}.zip ../publish
            }
            else {
              zip -r ../${{ matrix.os }}_resumer_${{ github.ref_name }}.zip ../publish
            }

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh release create ${{ github.ref_name }} ${{ matrix.os }}_resumer_${{ github.ref_name }}.zip --draft
