# good ref:https://github.com/ruby/ruby-dev-builder/blob/b0bf59a17c17985d4692243d4689c273f6348fa5/.github/workflows/build.yml#L40
name: Draft Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:

  setup-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        run: gh release create ${{ github.ref_name }} --draft --generate-notes

  publish:
    runs-on: ${{ matrix.os }}
    needs: setup-release
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]


    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish Resumer/ --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: ./publish/

      - name: Zip Files
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            mv ./publish/Resumer.exe ./publish/resumer.exe
            7z a ./${{ matrix.os }}_resumer_${{ github.ref_name }}.zip '.\publish\*'
            }
            else {
              mv ./publish/Resumer ./publish/resumer
              cd ./publish
              zip -1g ../${{ matrix.os }}_resumer_${{ github.ref_name }}.zip ./publish/*
              cd ..
            }

      - name: Upload Release Asset
        run: gh release upload ${{ github.ref_name }} ${{ matrix.os }}_resumer_${{ github.ref_name }}.zip
